// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Luis Ciber",
            "url": "https://www.luisciber.com/",
            "email": "luisciber640@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/luicib3r/shortly"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/shortcut": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shortcut"
                ],
                "summary": "Get Shortcuts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ShortcutDto"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shortcut"
                ],
                "summary": "Create Shortcut",
                "parameters": [
                    {
                        "description": "Create Shortcut",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateShortcutDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ShortcutDto"
                        }
                    }
                }
            }
        },
        "/api/shortcut/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shortcut"
                ],
                "summary": "Get Shortcut by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shortcut ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ShortcutDto"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Shortcut"
                ],
                "summary": "Delete Shortcut by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shortcut ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateShortcutDto": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "dtos.ShortcutDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "short": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shortly Service",
	Description:      "URL shortener service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
